/**
 * scripts/build-zcode-hooks.ts — build the ZCode process-hook bundles
 * (root script `hooks:build`; plan 20260908-hooks-cross-host contract D2).
 *
 * Bundles `hooks/src/mstar-write-gate.ts` with `bun build --target node`
 * (the hook runs via `"command": "node"` in hooks/hooks.json) into the
 * COMMITTED artifact `hooks/mstar-write-gate.mjs`. The ZCode plugin root IS
 * the repo checkout and the plugin pipeline has no build step, so the built
 * bundle is committed under a `@generated` banner; CI enforces freshness
 * (`bun run engine:build && bun run hooks:build && git diff --exit-code --
 * hooks/`). The `@mstar-harness/engine` glue is inlined — no bare engine
 * import may survive (asserted by the same-name bundle smoke).
 *
 * Repo convention: same-name test (scripts/build-zcode-hooks.test.ts) wired
 * into the CI "Test scripts" step.
 */
import { statSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");

export const HOOK_ENTRY_REL = "hooks/src/mstar-write-gate.ts";
export const HOOK_OUTFILE_REL = "hooks/mstar-write-gate.mjs";

/** Banner prepended to the bundle: marks the committed artifact as build
 * output and names the regeneration path (contract D2). Pure ASCII. */
export const GENERATED_BANNER =
  "#!/usr/bin/env node\n" +
  "// @generated by scripts/build-zcode-hooks.ts from hooks/src/mstar-write-gate.ts - do not edit; rebuild with `bun run hooks:build`.\n";

/** Rebuild the committed ZCode hook bundle in place. Deterministic output
 * (same tree -> byte-identical artifact) is load-bearing: the CI freshness
 * gate diffs the working tree against the committed file. Throws on build
 * failure so `hooks:build` and CI fail loud. */
export async function buildZcodeHooks(): Promise<{ outfile: string; bytes: number }> {
  // Bun.build without `outdir` builds to in-memory artifacts — write the
  // entry-point artifact ourselves (an `outfile` alone is not written).
  const result = await Bun.build({
    entrypoints: [join(ROOT, HOOK_ENTRY_REL)],
    target: "node",
    banner: GENERATED_BANNER,
  });
  if (!result.success) {
    const detail = result.logs.map((log) => String(log)).join("\n");
    throw new Error(`hooks:build failed for ${HOOK_ENTRY_REL}:\n${detail}`);
  }
  const entryArtifact = result.outputs.find((output) => output.kind === "entry-point");
  if (entryArtifact === undefined) {
    throw new Error(`hooks:build produced no entry-point artifact for ${HOOK_ENTRY_REL}`);
  }
  const outfile = join(ROOT, HOOK_OUTFILE_REL);
  await Bun.write(outfile, entryArtifact);
  return { outfile, bytes: statSync(outfile).size };
}

if (import.meta.main) {
  const { outfile, bytes } = await buildZcodeHooks();
  console.log(`hooks:build: ${relative(ROOT, outfile)} (${bytes} bytes, engine inlined)`);
}
